[tool.poetry]
name = "hello-django-world"
version = "0.1.0"
description = "your friendly django world"
authors = ["zac Gerber <Zgerber91@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
